### ISSUE TITLE
Thanks! (capturing 1x/minute)

### ISSUE THREAD

**Issue by lokijota** [MarekLani/VisionDevKit_CaptureModule#2]
Hey Marek,

just to let you know that I used your sample and modified it to just upload a photo every minute: I don't want to rely on the Person detection capabilities.

Where's what I did:

1- created a cronjobs file with content:

```text
* * * * * node /app/app.js > /dev/stdout
```

(the redirect is actually not working, I want it to go to the container logs but I get an error when I use the supposedly correct "> /proc/1/fd/1 2>/proc/1/fd/2")

2- changed dockerfile to:

```
FROM arm32v7/node:12-alpine3.11

WORKDIR /app/

RUN apk add  --no-cache ffmpeg

COPY package*.json ./

RUN npm install --production

COPY app.js ./

# copy crontabs for root user
COPY cronjobs /etc/crontabs/root

USER root

# start crond with log level 8 in foreground, output to stderr
CMD ["crond", "-f", "-d", "8"]
```

3- in app.js, I commented all the code block related to iothub and it's place just left `TakeAndUploadCaptureFromStream();`

Working fine. Images have ~220km each in my case. I'll do some processing in a function to find if there's significant change, and alert me in that case.

Thanks for putting in the work to code this :-).

**Comment by MarekLani** [comment]
Hi @lokijota I am glad, my code was helpful, interesting adaptation you made, thanks for sharing!
